# Generated by Django 3.1.4 on 2021-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210113_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, choices=[('Australian Capital Territory','Australian Capital Territory'),('New South Wales','New South Wales'),('Northern Territory','Northern Territory'),('Queensland','Queensland'),('South Australia','South Australia'),('Tasmania','Tasmania'),('Victoria','Victoria'),('Western Australia','Western Australia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
